// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyrtexTask.Data.EF;

#nullable disable

namespace MyrtexTask.Data.EF.Migrations
{
    [DbContext(typeof(MyrtexTaskDbContext))]
    partial class MyrtexTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyrtexTask.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12406d89-efec-48ef-bab6-fcb1c048bb5d"),
                            DateOfBirth = new DateTime(1995, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfEmployment = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Разработчики",
                            FullName = "Аполин С.Ю.",
                            Salary = 170000m
                        },
                        new
                        {
                            Id = new Guid("9a34cea2-91fe-4d9a-a746-291601bd574a"),
                            DateOfBirth = new DateTime(1997, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfEmployment = new DateTime(2022, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Разработчики",
                            FullName = "Волков А.В.",
                            Salary = 130000m
                        },
                        new
                        {
                            Id = new Guid("5c752058-3da8-41a6-ae30-ae555749e7a2"),
                            DateOfBirth = new DateTime(1996, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfEmployment = new DateTime(2021, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Поддержка",
                            FullName = "Воронов Е.В.",
                            Salary = 100000m
                        },
                        new
                        {
                            Id = new Guid("162c8c91-bc25-4228-9ffc-16bae5c499d2"),
                            DateOfBirth = new DateTime(1998, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfEmployment = new DateTime(2021, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Маркетинг",
                            FullName = "Елисеева А.С.",
                            Salary = 90000m
                        },
                        new
                        {
                            Id = new Guid("23f0ef2b-5a57-43d1-b6fc-9c47d56fed9c"),
                            DateOfBirth = new DateTime(1991, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfEmployment = new DateTime(2018, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Управление",
                            FullName = "Савин В.Г.",
                            Salary = 200000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
